
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdwawncmybyjthqovftk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkd2F3bmNteWJ5anRocW92ZnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODgyNjksImV4cCI6MjA2NTk2NDI2OX0.FjZT2268HR5O4q5wfefTBvcHsU7k8-76n1xAcRnjrWk";

console.log('Initializing Supabase client...');

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});

console.log('Supabase client initialized successfully');
